spring.application.name=agri-manager-backend

# ===============================
# DATASOURCE
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/agri_manager
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


agromonitoring.api.key = 0b62676dae2bdd1b2aa0e463c57262d8
agromonitoring.base.url=http://api.agromonitoring.com/agro/1.0


# ???????????????????????????????
# Open-Meteo Configuration
# ???????????????????????????????
open-meteo.base.url=https://api.open-meteo.com/v1